monsieurbiz_sylius_cms_page_admin:
  resource: |
    alias: monsieurbiz_cms_page.page
    section: admin
    templates: SyliusAdminBundle:Crud
    except: ['show']
    redirect: update
    grid: monsieurbiz_cms_page
    vars:
        all:
            subheader: monsieurbiz_cms_page.ui.pages_subheader
        index:
            icon: 'file alternate'
  type: sylius.resource

