imports:
    - { resource: "sylius/resources.yaml" }
    - { resource: "sylius/grid.yaml" }
    - { resource: "sylius/fixtures.yaml" }

sylius_labs_doctrine_migrations_extra:
    migrations:
        MonsieurBiz\SyliusCmsPagePlugin\Migrations: ~
